upstream qian_wenku_web {
    server 127.0.0.1:8000;
    keepalive 16;
}

server {
    listen 80;
    listen [::]:80;
    server_name wenku.qianxuesen.org;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name wenku.qianxuesen.org;

    ssl_certificate /etc/letsencrypt/live/wenku.qianxuesen.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/wenku.qianxuesen.org/privkey.pem;
    ssl_session_timeout 1d;
    ssl_session_cache shared:WENKU:10m;
    ssl_protocols TLSv1.2 TLSv1.3;

    add_header Referrer-Policy strict-origin-when-cross-origin always;
    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options SAMEORIGIN always;

    location / {
        proxy_pass http://qian_wenku_web;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 60s;
    }
}
